### ISSUE TITLE
Describe Staging: Error Message

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1110]
## Description

Received an error message in Describe. These were my actions leading to the message:
- successful log in
- navigated to the dash board
- opened a pending record and selected edit
- did not edit the content, but went back to the dashboard to look for a different record
- tried to open a "published" record and received the error message
- successfully went back to the dashboard
- tried to open other records, but received the error message each time

## Image shows the error message
<img width="1219" alt="Screen Shot 2023-05-01 at 5 15 38 PM" src="https://user-images.githubusercontent.com/50670293/235533604-81dd7d24-f20c-42e4-9061-163a8e51941b.png">

## Acceptance Criteria
- [ ] Diagnose the reason behind the error message
- [ ] Message will not appear and selections will work as expected

**Comment by hhkitsune** [comment]
Update: Others in PRDS are experiencing this same error message.

**Comment by hectorcorrea** [comment]
The error happens when editing any published record. The logs show a problem with a missing column in the `upload_snapshots` table:

```
F, [2023-05-03T14:00:54.961517 #710907] FATAL -- : [5f01e5db-6165-422e-b331-18ef6fdd8077]   
[5f01e5db-6165-422e-b331-18ef6fdd8077] ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column upload_snapshots.url does not exist
LINE 1: ...hots" WHERE "upload_snapshots"."work_id" = $1 AND "upload_sn...
                                                             ^
HINT:  Perhaps you meant to reference the column "upload_snapshots.uri".
):
[5f01e5db-6165-422e-b331-18ef6fdd8077]   
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/models/work.rb:480:in `block in new_s3_files'
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/models/work.rb:479:in `reject'
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/models/work.rb:479:in `new_s3_files'
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/models/work.rb:485:in `new_snapshots'
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/models/work.rb:491:in `current_snapshots'
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/models/work.rb:495:in `invalid_snapshots'
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/models/work.rb:528:in `reload_snapshots'
[5f01e5db-6165-422e-b331-18ef6fdd8077] app/controllers/works_controller.rb:69:in `show'
```

**Comment by carolyncole** [comment]
@hectorcorrea https://github.com/pulibrary/pdc_describe/pull/1113 I tested this locally.

Unfortunately we merged a PR that modified the database create. 😢 I think that might have been me...

**Comment by hectorcorrea** [comment]
Table in staging:

```
pdc_describe_staging=> \d upload_snapshots
                                          Table "public.upload_snapshots"
   Column   |              Type              | Collation | Nullable |                   Default                    
------------+--------------------------------+-----------+----------+----------------------------------------------
 id         | bigint                         |           | not null | nextval('upload_snapshots_id_seq'::regclass)
 uri        | character varying              |           | not null | 
 work_id    | bigint                         |           | not null | 
 created_at | timestamp(6) without time zone |           | not null | 
 updated_at | timestamp(6) without time zone |           | not null | 
Indexes:
    "upload_snapshots_pkey" PRIMARY KEY, btree (id)
    "index_upload_snapshots_on_work_id" btree (work_id)
Foreign-key constraints:
    "fk_rails_0e01bc9fbb" FOREIGN KEY (work_id) REFERENCES works(id)
```

Table as we create it:

```
  create_table "upload_snapshots", force: :cascade do |t|
    t.string "filename"
    t.string "url"
    t.bigint "version"
    t.string "checksum"
    t.bigint "work_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["work_id"], name: "index_upload_snapshots_on_work_id"
  end
```

**Comment by hectorcorrea** [comment]
Fixed with PR https://github.com/pulibrary/pdc_describe/pull/1113

Database in staging now has the correct fields:

```
pdc_describe_staging=> \d upload_snapshots
                                          Table "public.upload_snapshots"
   Column   |              Type              | Collation | Nullable |                   Default                    
------------+--------------------------------+-----------+----------+----------------------------------------------
 id         | bigint                         |           | not null | nextval('upload_snapshots_id_seq'::regclass)
 url        | character varying              |           | not null | 
 work_id    | bigint                         |           | not null | 
 created_at | timestamp(6) without time zone |           | not null | 
 updated_at | timestamp(6) without time zone |           | not null | 
 filename   | character varying              |           |          | 
 version    | bigint                         |           |          | 
 checksum   | character varying              |           |          | 
Indexes:
    "upload_snapshots_pkey" PRIMARY KEY, btree (id)
    "index_upload_snapshots_on_work_id" btree (work_id)
Foreign-key constraints:
    "fk_rails_0e01bc9fbb" FOREIGN KEY (work_id) REFERENCES works(id)
```
