### ISSUE TITLE
Data migration bug: The Content-MD5 you specified was invalid

### ISSUE THREAD

**Issue by bess** [pulibrary/pdc_describe#1273]
Automated data migration is broken. When you push the button it gives the attached error, but no error is raised to Honeybadger. 

<img width="704" alt="Screenshot 2023-06-20 at 2 00 10 PM" src="https://github.com/pulibrary/pdc_describe/assets/65608/4004341d-c2f7-4265-8eaf-6c13cc067858">

**Comment by bess** [comment]
The error is also present when we try to migrate the files via the command line: 
```
Migrating Files from dspace to PDC for Work Sowing the Seeds for More Usable Web Archives: A Usability Study of Archive-It
rake aborted!
Aws::S3::Errors::InvalidDigest: The Content-MD5 you specified was invalid.
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-s3-1.113.2/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-s3-1.113.2/lib/aws-sdk-s3/plugins/dualstack.rb:27:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-s3-1.113.2/lib/aws-sdk-s3/plugins/accelerate.rb:56:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/seahorse/client/plugins/response_target.rb:24:in `call'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-core-3.130.2/lib/seahorse/client/request.rb:72:in `send_request'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/aws-sdk-s3-1.113.2/lib/aws-sdk-s3/client.rb:12367:in `put_object'
/opt/pdc_describe/releases/20230620133220/app/services/s3_query_service.rb:216:in `upload_file'
/opt/pdc_describe/releases/20230620133220/app/services/pul_dspace_aws_connector.rb:18:in `block in upload_to_s3'
/opt/pdc_describe/releases/20230620133220/app/services/pul_dspace_aws_connector.rb:12:in `map'
/opt/pdc_describe/releases/20230620133220/app/services/pul_dspace_aws_connector.rb:12:in `upload_to_s3'
/opt/pdc_describe/releases/20230620133220/app/services/pul_dspace_migrate.rb:112:in `upload_dspace_files'
/opt/pdc_describe/releases/20230620133220/app/services/pul_dspace_migrate.rb:103:in `migrate_dspace'
/opt/pdc_describe/releases/20230620133220/app/services/pul_dspace_migrate.rb:24:in `migrate'
/opt/pdc_describe/releases/20230620133220/lib/tasks/dspace.rake:11:in `block (2 levels) in <main>'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/ddtrace-1.11.1/lib/datadog/tracing/contrib/rake/instrumentation.rb:30:in `execute'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `load'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:23:in `run'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/cli.rb:483:in `exec'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/opt/pdc_describe/shared/bundle/ruby/3.1.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => dspace:migrate_content
(See full trace by running task with --trace)
```

**Comment by bess** [comment]
Maybe this is to do with needing to base-64 encode the MD5? 
https://stackoverflow.com/questions/33577617/amazon-s3-gives-invaliddigest-the-content-md5-you-specified-was-invalid

**Comment by kelynch** [comment]
@bess I think that sounds right.  As part of [this ADR](https://github.com/pulibrary/pdc_describe/blob/main/architecture-decisions/0009-Additional-checksums.md), Carolyn and I tested the MD5s that come from this [S3 Python command-line tool](https://github.com/aws-samples/amazon-s3-checksum-verification) and it returns the base-64 encoded checksum, not the hexdigest.  The base-64 checksums matched during our testing, between testing with the Ruby digest module and comparing the result to the S3 Python script above.
