### ISSUE TITLE
Describe Form: Error message during new submission (production)

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/pdc_describe#1493]
## Description

An error message was experienced during a new submission to PDC Describe in production. In all cases the error message could be bypassed by using the back button and proceeding with the submission workflow. These descriptions detail where the message occurred during the submission process:
- Error page appeared when user pressed save after replacing the README. The user then used the back button and saw that his file had, in fact, been replaced by the new README. He was then able to save and proceed without experiencing the error message.
- The error message appeared when the user tried to click on the README from the record page in Describe. However, nothing seemed wrong and the message went away when he pressed the back button which returned him to the record page.
- The error message appeared again when the user edited the keywords for the submission.The message appeared after pressing save, but the user used the back button again and saved and the work for the keywords was already saved.

The work that was being created is this: 
https://pdc-describe-prod.princeton.edu/describe/works/116

## Acceptance Criteria
- [ ] Diagnose why the messages are appearing
- [ ] The error messages should not appear for expected activity during a submission
- [ ] Please inquire with Sarah (the curator for the submission) should you need clarification for the error message occurrences.

**Comment by hectorcorrea** [comment]
HoneyBadger logged the following errors in production around the time users were entering this submission. None of them looks like the culprit, but it might be worthwhile looking closely into them:
* https://app.honeybadger.io/projects/99214/faults/99824271/01H9G3ZPT148BKQEP1F2PFMD2K?q=occurred.after%3A%222023-09-01+12%3A00+UTC-4%22
* https://app.honeybadger.io/projects/99214/faults/96805213?q=occurred.after%3A%222023-09-01+12%3A00+UTC-4%22
* https://app.honeybadger.io/projects/99214/faults/99855129/01H990H1T28CCWE6327BK15JPY?q=occurred.after%3A%222023-09-01+12%3A00+UTC-4%22
* https://app.honeybadger.io/projects/99214/faults/95637180/01H98QKQ00XHJQ54GYR1DNB2XM?q=occurred.after%3A%222023-09-01+12%3A00+UTC-4%22

**Comment by carolyncole** [comment]
[extract-2023-09-06T14_43_53.923Z.csv](https://github.com/pulibrary/pdc_describe/files/12539050/extract-2023-09-06T14_43_53.923Z.csv)

**Comment by hectorcorrea** [comment]
The log in production for `pdc-describe-prod1`. The ActiveJob error shows 100+ times.

```
$ zcat production.log.5.gz | grep 2023-09-01
F, [2023-09-01T18:30:05.787937 #1214] FATAL -- : [121383e1-e53b-4ebc-b4d7-fc45918e1e56] [dd.env=production dd.service=pdc-describe dd.trace_id=182635188656940886 dd.span_id=4150355319617453034]   
F, [2023-09-01T18:30:58.013043 #1214] FATAL -- : [c7bd20c3-8990-47c7-821d-4120f3be0510] [dd.env=production dd.service=pdc-describe dd.trace_id=2385011787787716581 dd.span_id=3040769026741463668]   
F, [2023-09-01T18:36:45.927259 #1214] FATAL -- : [ed609b62-8e10-41f1-9151-96f857b87b94] [dd.env=production dd.service=pdc-describe dd.trace_id=2913213036649808835 dd.span_id=3277389946972718907]   
E, [2023-09-01T20:02:59.991037 #850] ERROR -- : [ActiveJob] [ApprovedFileMoveJob] [f28497ef-1333-4a14-9492-25297fb4823c] Error performing ApprovedFileMoveJob (Job ID: f28497ef-1333-4a14-9492-25297fb4823c) from Sidekiq(default) in 9.96ms: ActiveRecord::RecordNotFound (Couldn't find ApprovedUploadSnapshot with 'id'=203):
E, [2023-09-01T20:02:59.993172 #850] ERROR -- : [ActiveJob] [ApprovedFileMoveJob] [43f807f4-a29e-46f5-bbc6-0d14415bee1f] Error performing ApprovedFileMoveJob (Job ID: 43f807f4-a29e-46f5-bbc6-0d14415bee1f) from Sidekiq(default) in 11.03ms: ActiveRecord::RecordNotFound (Couldn't find ApprovedUploadSnapshot with 'id'=203):
E, [2023-09-01T20:02:59.994621 #850] ERROR -- : [ActiveJob] [ApprovedFileMoveJob] [1dede74c-077f-46a0-b327-32630e16a245] Error performing ApprovedFileMoveJob (Job ID: 1dede74c-077f-46a0-b327-32630e16a245) from Sidekiq(default) in 10.04ms: ActiveRecord::RecordNotFound (Couldn't find ApprovedUploadSnapshot with 'id'=203):
E, [2023-09-01T20:03:00.002787 #850] ERROR -- : [ActiveJob] [ApprovedFileMoveJob] [cb056109-fe6b-438e-918e-e697f0edd42a] Error performing ApprovedFileMoveJob (Job ID: cb056109-fe6b-438e-918e-e697f0edd42a) from Sidekiq(default) in 19.1ms: ActiveRecord::RecordNotFound (Couldn't find ApprovedUploadSnapshot with 'id'=203):
```

**Comment by carolyncole** [comment]
```
F, [2023-09-01T18:36:45.139827 #1225] FATAL -- : [e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490]
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490] NoMethodError (undefined method `length' for nil:NilClass

      elsif checksum1.length < checksum2.length
                     ^^^^^^^):
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490]
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490] app/models/upload_snapshot.rb:75:in `checksum_compare'
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490] app/models/upload_snapshot.rb:46:in `block in index'
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490] app/models/upload_snapshot.rb:46:in `index'
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490] app/models/upload_snapshot.rb:46:in `index'
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490] app/models/upload_snapshot.rb:50:in `match?'
[e994ff31-75ea-46ab-a441-c31cf475782a] [dd.env=production dd.service=pdc-describe dd.trace_id=4310115143797449925 dd.span_id=3799406911436867490] app/models/upload_snapshot.rb:20:in `block in snapshot_modifications'
/18:36:45                                                                                                                                            
```

**Comment by carolyncole** [comment]
```
F, [2023-09-01T18:30:57.122001 #1225] FATAL -- : [d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400]
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] NoMethodError (undefined method `length' for nil:NilClass

      elsif checksum1.length < checksum2.length
                     ^^^^^^^):
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400]
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:75:in `checksum_compare'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:46:in `block in index'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:46:in `index'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:46:in `index'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:50:in `match?'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:20:in `block in snapshot_modifications'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:19:in `each'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/upload_snapshot.rb:19:in `snapshot_modifications'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/models/work.rb:488:in `reload_snapshots'
[d15d1e17-e415-4aa6-a8b8-04c6b1cce723] [dd.env=production dd.service=pdc-describe dd.trace_id=796043046856475110 dd.span_id=2834079997070150400] app/controllers/works_controller.rb:72:in `show'
```
