### ISSUE TITLE
Error in Show page for works in production

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#358]
Loading this work in production https://pdc-describe-prod.princeton.edu/describe/works/17 throws an error. This is what the log shows:

```
I, [2022-08-31T16:59:24.581607 #30804]  INFO -- : [2038556c-bd66-4745-a1e6-fdfde8df703a] Processing by WorksController#show as HTML
I, [2022-08-31T16:59:24.581667 #30804]  INFO -- : [2038556c-bd66-4745-a1e6-fdfde8df703a]   Parameters: {"id"=>"17"}
I, [2022-08-31T16:59:24.669414 #30804]  INFO -- : [2038556c-bd66-4745-a1e6-fdfde8df703a] Completed 500 Internal Server Error in 88ms (ActiveRecord: 10.1ms | Allocations: 8137)
F, [2022-08-31T16:59:24.670852 #30804] FATAL -- : [2038556c-bd66-4745-a1e6-fdfde8df703a]   
[2038556c-bd66-4745-a1e6-fdfde8df703a] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_active_storage_blobs_on_key"
DETAIL:  Key (key)=(10.80021/8jg2-8855/17/Screen Shot 2022-08-25 at 9.48.29 AM.png) already exists.
):
[2038556c-bd66-4745-a1e6-fdfde8df703a]   
[2038556c-bd66-4745-a1e6-fdfde8df703a] app/models/work.rb:332:in `add_pre_curation_uploads'
[2038556c-bd66-4745-a1e6-fdfde8df703a] app/controllers/works_controller.rb:39:in `block in show'
[2038556c-bd66-4745-a1e6-fdfde8df703a] app/controllers/works_controller.rb:38:in `each'
[2038556c-bd66-4745-a1e6-fdfde8df703a] app/controllers/works_controller.rb:38:in `show'
```

I am not sure if this is bad data or an error in the code.

The error also happens for work https://pdc-describe-prod.princeton.edu/describe/works/15

**Comment by carolyncole** [comment]
Maybe there are two files that are the same in two separate buckets.

**Comment by carolyncole** [comment]
The works 15, 17 and 18 all error on production.  Creating a new work and adding files to correct bucket in S3 does not produce the error.

**Comment by hectorcorrea** [comment]
@carolyncole I would be OK deleting these records from the database if you think the problem is data that we messed up during the back and forth on the way we manage files.

**Comment by carolyncole** [comment]
@hectorcorrea I'm going to keep digging and see what I see.  Let's not delete them until we understand what the issue is...

**Comment by carolyncole** [comment]
It seems to be a vestige from changing the name of the attachment
They are `deposit_uploads` not `pre_curation_uploads`
```
#<ActiveStorage::Attachment:0x0000555b681138e8 id: 2, name: "deposit_uploads", record_type: "Work", record_id: 15, blob_id: 2, created_at: Wed, 24 Aug 2022 20:37:56.247043000 UTC +00:00>
```

**Comment by carolyncole** [comment]
I ran this in the rails console to solve the specific issue:
```
ActiveStorage::Attachment.where(name: "deposit_uploads").each{|attach| attach.name = "pre_curation_uploads"; attach.save}
```
