### ISSUE TITLE
Test failure on main

### ISSUE THREAD

**Issue by mccalluc** [pulibrary/pdc_describe#777]
https://app.circleci.com/pipelines/github/pulibrary/pdc_describe/2211/workflows/ca2bb26d-90ec-4e34-9795-045ebf5af78a/jobs/6865
```
  1) PDCSerialization::Datacite resource JSON to Datacite XML handles spec/fixtures/resource-to-datacite/basic.resource.yaml
     Failure/Error:
       titles.each do |title|
         resource.titles << PDCMetadata::Title.new(title: title["title"], title_type: title["title_type"])
       end
     
     NoMethodError:
       undefined method `each' for "titles":String
     # ./app/models/pdc_metadata/resource.rb:119:in `set_titles'
     # ./app/models/pdc_metadata/resource.rb:69:in `new_from_json'
     # ./spec/models/pdc_serialization/datacite_spec.rb:256:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:107:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:106:in `block (2 levels) in <top (required)>'
```
The PRs had passing tests, but maybe this is the rare case where a change on the trunk has a logic bug when combined with the a branch that doesn't appear until after the merge.

**Comment by mccalluc** [comment]
Should be fixed by https://github.com/pulibrary/pdc_describe/commit/a5cbc724a6feb2047ba71eb21123335e1106266e  which I pushed to main accidentally. Will close when tests pass.

**Comment by mccalluc** [comment]
CI is happy: Closing.
