### ISSUE TITLE
Error performing ActiveStorage::AnalyzeJob

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pdc_describe#961]
I've seen these errors in my local logs for files added directly to S3 (and later on attached to the Work through our code):

NOTE: I did not see these messages logged in Staging so I am not sure if this is a real problem.

```
[ActiveJob] [ActiveStorage::AnalyzeJob] [707bb91d-ea28-413c-be6c-f4492ca29a3c] Performing ActiveStorage::AnalyzeJob (Job ID: 707bb91d-ea28-413c-be6c-f4492ca29a3c) from Async(default) enqueued at 2023-02-06T20:53:43Z with arguments: #<GlobalID:0x00007fa45d87bb68 @uri=#<URI::GID gid://drds-rails-template/ActiveStorage::Blob/13253>>
[ActiveJob] [ActiveStorage::AnalyzeJob] [707bb91d-ea28-413c-be6c-f4492ca29a3c]   S3 Storage (605.3ms) Downloaded file from key: 10.34770/tbd/12/IMG_4142.JPG
[ActiveJob] [ActiveStorage::AnalyzeJob] [707bb91d-ea28-413c-be6c-f4492ca29a3c] Error performing ActiveStorage::AnalyzeJob (Job ID: 707bb91d-ea28-413c-be6c-f4492ca29a3c) from Async(default) in 622.14ms: NameError (uninitialized constant ActiveStorage::Analyzer::ImageAnalyzer::MiniMagick
Did you mean?  MiniMime):
/Users/correah/.gem/ruby/3.0.3/gems/activestorage-6.1.6.1/lib/active_storage/analyzer/image_analyzer.rb:46:in `rescue in read_image'
/Users/correah/.gem/ruby/3.0.3/gems/activestorage-6.1.6.1/lib/active_storage/analyzer/image_analyzer.rb:31:in `read_image'
/Users/correah/.gem/ruby/3.0.3/gems/activestorage-6.1.6.1/lib/active_storage/analyzer/image_analyzer.rb:21:in `metadata'
/Users/correah/.gem/ruby/3.0.3/gems/activestorage-6.1.6.1/app/models/active_storage/blob/analyzable.rb:51:in `extract_metadata_via_analyzer'
/Users/correah/.gem/ruby/3.0.3/gems/activestorage-6.1.6.1/app/models/active_storage/blob/analyzable.rb:29:in `analyze'
/Users/correah/.gem/ruby/3.0.3/gems/activestorage-6.1.6.1/app/jobs/active_storage/analyze_job.rb:11:in `perform'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/execution.rb:48:in `block in perform_now'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:21:in `block in instrument'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `block in instrument'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in `instrument'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:31:in `instrument'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/logging.rb:22:in `block in tag_logger'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/logging.rb:22:in `tag_logger'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/execution.rb:47:in `perform_now'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/execution.rb:25:in `block in execute'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb:72:in `block in wrap'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/reloader.rb:71:in `wrap'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `instance_exec'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/execution.rb:23:in `execute'
/Users/correah/.gem/ruby/3.0.3/gems/activejob-6.1.6.1/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/ivar.rb:169:in `safe_execute'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/scheduled_task.rb:298:in `process_task'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/timer_set.rb:165:in `block (2 levels) in process_tasks'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
/Users/correah/.gem/ruby/3.0.3/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
[ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 707bb91d-ea28-413c-be6c-f4492ca29a3c) to Async(default) at 2023-02-06 21:30:12 UTC with arguments: #<GlobalID:0x00007fa46cc02110 @uri=#<URI::GID gid://drds-rails-template/ActiveStorage::Blob/13253>>
Retrying ActiveStorage::AnalyzeJob in 1477 seconds, due to a ActiveStorage::IntegrityError.
```

**Comment by carolyncole** [comment]
@hectorcorrea I saw these, but since we do not really care about it happening I just ignored them.  That may  not be the best approach 😁.  Thanks for ticketing.

**Comment by hectorcorrea** [comment]
More (interesting) information on these built-it analyzers: https://stackoverflow.com/questions/56445881/rails-how-to-disable-activestorage-analyzers-and-previewers

**Comment by carolyncole** [comment]
Since we are moving away from Active Storage we are closing this
